{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "API GuthBarber",
    "description": "Documentação da API da GuthBarber"
  },
  "host": "localhost:3000",
  "basePath": "",
  "tags": [],
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/clientes": {
      "post": {
        "tags": [
          "Clientes"
        ],
        "summary": "Insere um cliente.",
        "description": "",
        "parameters": [
          {
            "name": "json",
            "in": "body",
            "description": "Dados para inserir um aluno",
            "type": "json",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number",
                  "example": 1
                },
                "nome": {
                  "type": "string",
                  "example": "Guilherme Guth Zahn"
                },
                "cpfcnpj": {
                  "type": "string",
                  "example": "073.926.459-19"
                },
                "rginsc": {
                  "type": "string",
                  "example": "152.650.152"
                },
                "telefone": {
                  "type": "string",
                  "example": "(49)988740497"
                },
                "email": {
                  "type": "string",
                  "example": "guilhermeguthzgmail.com"
                },
                "endereco": {
                  "type": "string",
                  "example": "Av. Sao Paulo"
                },
                "numero": {
                  "type": "number",
                  "example": 2999
                },
                "bairro": {
                  "type": "string",
                  "example": "Pioneiro"
                },
                "complemento": {
                  "type": "string",
                  "example": "Residencial Mantelli Apt 402-B"
                },
                "municipio": {
                  "type": "string",
                  "example": "Pinhalzinho"
                },
                "cep": {
                  "type": "string",
                  "example": "89870-000"
                },
                "uf": {
                  "type": "string",
                  "example": "SC"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "get": {
        "tags": [
          "Clientes"
        ],
        "summary": "Busca lista de Clientes.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/clientes/{id}": {
      "delete": {
        "tags": [
          "Clientes"
        ],
        "summary": "Deleta um cliente selecionado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "id do Cliente",
            "value": "1"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/colaboradores": {
      "post": {
        "tags": [],
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "get": {
        "tags": [
          "Colaboradores"
        ],
        "summary": "Busca lista de Colaboradores.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/colaboradores/{id}": {
      "delete": {
        "tags": [
          "Colaboradores"
        ],
        "summary": "Deleta um colaborador selecionado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "id do Colaborador",
            "value": "1"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/fornecedores": {
      "post": {
        "tags": [],
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "get": {
        "tags": [
          "Fornecedores"
        ],
        "summary": "Busca lista de Fornecedores.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/fornecedores/{id}": {
      "delete": {
        "tags": [
          "Fornecedores"
        ],
        "summary": "Deleta um Fornecedor selecionado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "id do Fornecedore",
            "value": "1"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/itens": {
      "post": {
        "tags": [],
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "get": {
        "tags": [
          "Itens"
        ],
        "summary": "Busca lista de Itens.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/itens/{id}": {
      "delete": {
        "tags": [
          "Itens"
        ],
        "summary": "Deleta um item selecionado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "id do item",
            "value": "1"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/tipoItem": {
      "post": {
        "tags": [],
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "get": {
        "tags": [
          "Tipo Item"
        ],
        "summary": "Busca lista de Tipo de Item.",
        "description": "",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/tipoItem/{id}": {
      "delete": {
        "tags": [
          "Tipo Item"
        ],
        "summary": "Deleta um tipo item selecionado.",
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "id do tipo item",
            "value": "1"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    }
  },
  "definitions": {}
}